name: Zijing Code Report

on:
  # 每天北京时间 08:36, 14:36, 20:36 (utc+8) 打卡
  schedule:
    - cron: "36 0,6,12 * * *"

jobs:
  submit_report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        python3 report_zijing_code.py
      env: # Or as an environment variable
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PASS: ${{ secrets.USER_PASS }}
